"""Retain this assignment's evidence once, with portable names and SHA-256 readback."""
import hashlib, json, re, sys, zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

repo = Path(__file__).resolve().parents[3]
destination = Path(__file__).resolve().parent
main = Path(sys.argv[1]).resolve()
results = repo / 'TestResults'
files = {}
def add(path, name):
    path = Path(path)
    assert path.is_file() and name not in files and not Path(name).is_absolute() and '..' not in Path(name).parts
    files[name] = path
def directory(path, prefix, skip_data=False):
    for file in sorted(path.rglob('*')):
        if file.is_file():
            relative = file.relative_to(path)
            if skip_data and relative.parts[0] == 'data':
                if file.name != 'gantt-fixture.json': continue
            add(file, prefix + '/' + relative.as_posix())
for run in sorted((results / 'issue61-65').iterdir()):
    if run.is_dir(): directory(run, 'replays/' + run.name, True)
directory(main / 'TestResults/issue61-65/structural-a-cold-01', 'replays/structural-a-cold-01', True)
for name in ['ui-integration', 'e2e', 'structural-core-regression', 'structural-executed-source', 'structural-authority', 'desktop-observer-unavailable']:
    directory(results / name, name)
for pattern in ['recycle-*.log', 'recycle-*.jsonl', 'desktop-observer-build-*.log']:
    for file in sorted(results.glob(pattern)): add(file, 'logs/' + file.name)
add(main / 'TestResults/issue65-driver-build-20260923.log', 'logs/original-71-driver-build.log')
temp_images = set()
for stdout in (results / 'ui-integration').glob('*/stdout.log'):
    for match in re.findall(r'Rendered review evidence: (.+\.png)', stdout.read_text(encoding='utf-8-sig')):
        image = Path(match.strip())
        assert image.parent.name.startswith('ghpb-review-')
        if image.is_file(): temp_images.add(image)
for image in sorted(temp_images):
    for file in sorted(image.parent.iterdir()):
        if file.is_file() and file.suffix in ['.json', '.png']:
            name = 'rendered/' + image.parent.name + '/' + file.name
            if name not in files: add(file, name)

ledger = []
for name, file in sorted(files.items()):
    if file.name not in ['diagnostic.trx', 'e2e.trx', 'core.trx', 'results.xml']: continue
    tree = ET.parse(file)
    if file.suffix == '.trx':
        counters = tree.find('.//{*}Counters')
        if counters is None: continue
        counts = {k: int(counters.get(k, 0)) for k in ['total', 'executed', 'passed', 'failed', 'notExecuted']}
        failures = [node.text for node in tree.findall('.//{*}ErrorInfo/{*}Message')]
    else:
        counts = {k: int(tree.getroot().get(k, 0)) for k in ['total', 'passed', 'failed', 'skipped', 'inconclusive']}
        failures = [node.text for node in tree.findall('.//failure/message')]
    ledger.append(dict(path=name, counts=counts, failures=failures))
(destination / 'run-ledger.json').write_text(json.dumps(ledger, ensure_ascii=False, indent=2), encoding='utf-8')

archive = destination / 'raw-evidence.zip'
assert not archive.exists(), 'Prior archive is retained; do not overwrite.'
manifest = []
secret_pattern = re.compile(rb'(?:ghp_[A-Za-z0-9]{25,}|github_pat_[A-Za-z0-9_]{30,})')
with zipfile.ZipFile(archive, 'x', zipfile.ZIP_DEFLATED, compresslevel=6) as package:
    for name, file in sorted(files.items()):
        data = file.read_bytes()
        if file.suffix in ['.json', '.jsonl', '.txt', '.log', '.xml', '.trx', '.patch', '.diff']:
            assert not secret_pattern.search(data), 'Secret-pattern review required: ' + name
        manifest.append(dict(path=name, bytes=len(data), sha256=hashlib.sha256(data).hexdigest()))
        package.writestr(name, data)
with zipfile.ZipFile(archive) as package:
    assert package.testzip() is None
    for item in manifest: assert hashlib.sha256(package.read(item['path'])).hexdigest() == item['sha256']
index = dict(archive=archive.name, sha256=hashlib.sha256(archive.read_bytes()).hexdigest(), bytes=archive.stat().st_size,
    files=manifest, verifiedReadback=True,
    runtimeData='Per-run initial/final checkpoint and fixture metadata are included. Duplicate mutable seed-root copies are retained locally, not duplicated in this archive. Other seed files are regenerated by the recorded fixture command.',
    original71='The inherited #71 raw-evidence.zip is referenced, not copied here.')
(destination / 'artifact-index.json').write_text(json.dumps(index, indent=2))
print(json.dumps({k:v for k,v in index.items() if k != 'files'})); print('verified files:', len(manifest))
