name: ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'ga'
      - run: dotnet build GhProjectsBoards.sln --configuration Release
